"""Add phone_DOB_gender

Revision ID: 74ab73e1a50a
Revises: add_user_profile_table
Create Date: 2026-04-06 10:34:48.367501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74ab73e1a50a'
down_revision: Union[str, Sequence[str], None] = 'add_user_profile_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('user_profile', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('user_profile', sa.Column('gender', sa.String(length=20), nullable=True))
    op.drop_constraint(op.f('user_profile_user_id_key'), 'user_profile', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_profile_user_id_key'), 'user_profile', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('user_profile', 'gender')
    op.drop_column('user_profile', 'date_of_birth')
    op.drop_column('user_profile', 'phone')
    # ### end Alembic commands ###
