// Centralised route constants — logic only, no UI impact
export const ROUTES = {
  HOME:                   '/',
  LOGIN:                  '/login',
  SIGNUP:                 '/signup',
  FORGOT_PASSWORD:        '/forgot-password',
  EMAIL_VERIFICATION:     '/email-verification',
  RESET_PASSWORD:         '/reset-password',
  ACCOUNT_CREATED:        '/account-created',
  ONBOARDING_STEP_1:      '/onboarding/step-1',
  ONBOARDING_STEP_2:      '/onboarding/step-2',
  ONBOARDING_STEP_3:      '/onboarding/step-3',
  ONBOARDING_STEP_4:      '/onboarding/step-4',
  ONBOARDING_SUMMARY:     '/onboarding/summary',
  ONBOARDING_COMPLETION:  '/onboarding/completion',
  DASHBOARD:              '/dashboard',
  DASHBOARD_ALT:          '/dashboard/alt',
  INSIGHTS:               '/insights',
  INSIGHTS_DESKTOP:       '/insights/desktop',
  SIMULATOR:              '/simulator',
  TIMELINE:               '/timeline',
  RISK_EXPLANATION:       '/risk-explanation',
  RECOMMENDATIONS:        '/recommendations',
  RISK_REPORT:            '/risk-report',
  LAB_RESULTS:            '/lab-results',
  MEDICAL_REPORTS:        '/medical-reports',
  SLEEP:                  '/sleep',
  DEVICES:                '/devices',
  GOOGLE_FIT_SETTINGS:    '/device-settings/google-fit',
  DEVICE_SETTINGS:        '/device-settings/:deviceId',
  UPLOAD:                 '/upload',
  REPORT_PROCESSING:      '/report-processing',
  UPLOAD_SUCCESS:         '/upload-success',
  CONSULTATION:           '/consultation',
  DOCTOR_PROFILE:         '/consultation/doctor/:id',
  APPOINTMENT_CONFIRM:    '/consultation/confirm',
  CONSULTATION_HISTORY:   '/consultation/history',
  SETTINGS:               '/settings',
  SETTINGS_PROFILE:       '/settings/profile',
  SETTINGS_SECURITY:      '/settings/security',
  SETTINGS_PRIVACY:       '/settings/privacy',
  SETTINGS_NOTIFICATIONS: '/settings/notifications',
  SETTINGS_PASSWORD:      '/settings/password',
  SETTINGS_DELETE:        '/settings/delete',
  SECURITY_AUDIT:         '/settings/security-audit',
  LOGOUT:                 '/logout',
  NOTIFICATIONS:          '/notifications',
  NOTIFICATIONS_HISTORY:  '/notifications/history',
  ALERT_DETAILS:          '/notifications/alert/:id',
  EMERGENCY_ALERT:        '/notifications/emergency',
  HELP:                   '/help',
  HELP_SEARCH:            '/help/search',
  HELP_ARTICLE:           '/help/article/:slug',
  TERMS:                  '/terms',
  PRIVACY:                '/privacy',
  DATA_CONSENT:           '/data-consent',
  LOADING:                '/loading',
  STATUS:                 '/status',
  WHATS_NEW:              '/whats-new',
  NOT_FOUND:              '/404',
  SERVER_ERROR:           '/500',
  MAINTENANCE:            '/maintenance',
  AQI_MONITOR:            '/aqi-monitor',
  // ── Alias constants (used by pages but previously undeclared) ──────────────
  LANDING:                '/',                       // alias for HOME
  DEVICE_MANAGER:         '/devices',                // alias for DEVICES
  SLEEP_ANALYSIS:         '/sleep',                  // alias for SLEEP
  PROFILE:                '/settings/profile',       // alias for SETTINGS_PROFILE
  REPORTS:                '/medical-reports',        // alias for MEDICAL_REPORTS
};
